export const lightTheme = {
  name: 'light',
  body: '#FFF',
  primary: '#093579',
  primaryDark: '#072E69',
  secondary: '#082C63',
  text: '#212529',
  textMuted: '#6C757D',
  link: '#777777',
  linkHover: '#555',
  linkPrimary: '#007BFF',
  linkPrimaryHover: '#0056B3',
  secondaryText: '#999999',
  secondaryHeading: '#777',
  secondaryAltHeading: '#555',
  border: '#DEE2E6',
  backgroundLight: '#F8F9FA',
  backgroundHighlight: '#EFEFEF',
  disabledInput: '#E9ECEF',
  searchFocus: '#FFF',
  searchText: '#FFF',
  searchTextFocus: '#212529',
  dropdownText: '#FFF'
};

export const darkTheme = {
  name: 'dark',
  body: '#363537',
  primary: '#222222',
  primaryDark: '#111',
  secondary: '#111',
  text: '#FAFAFA',
  textMuted: '#AAA',
  link: '#DDDDDD',
  linkHover: '#BBB',
  linkPrimary: '#8CBFF7',
  linkPrimaryHover: '#539FF1',
  secondaryText: '#BBB',
  secondaryHeading: '#AAA',
  secondaryAltHeading: '#CCC',
  border: '#4D4F50',
  backgroundLight: '#2E2E2E',
  backgroundHighlight: '#222222',
  disabledInput: '#5E5D5F',
  searchFocus: '#111',
  searchText: '#FFF',
  searchTextFocus: '#FFF',
  dropdownText: '#FAFAFA'
};
